print("Persona: ¡Hola, pequeño! ¿Cómo estás hoy?")
print("Gato: Miau. (Bien, supongo. ¿Tienes algo interesante?)")
print("Persona: ¿Interesante? Bueno, estoy disfrutando del sol. ¿A ti te gusta el sol?")
print("Gato: Prrr... El sol es cálido. Prefiero una siesta en un lugar tranquilo.")
print("Persona: Entiendo. ¿Y qué has estado haciendo hoy?")
print("Gato: He estado observando pájaros desde la ventana. Uno casi entra.")
print("Persona: ¡Oh! Eso suena emocionante. ¿Tienes hambre?")
print("Gato: Miau. (Tal vez un poco.)")
print("Persona: Bueno, te dejaré ir entonces. ¡Que tengas un buen día!")
print("Gato: Miau. (Tú también.)")